"""add_hold_until_to_appointments

Revision ID: 414e3d9cfb5f
Revises: 3f9419c424c5
Create Date: 2026-08-21 20:49:43.251220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414e3d9cfb5f'
down_revision: Union[str, None] = '3f9419c424c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('hold_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_appointments_doctor_date_slot', 'appointments', ['doctor_id', 'appointment_date', 'start_time'], unique=False)
    op.create_index(op.f('ix_appointments_hold_until'), 'appointments', ['hold_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_hold_until'), table_name='appointments')
    op.drop_index('ix_appointments_doctor_date_slot', table_name='appointments')
    op.drop_column('appointments', 'hold_until')
    # ### end Alembic commands ###
