"""add_symptoms_to_appointments

Revision ID: 5dda6c850acd
Revises: 414e3d9cfb5f
Create Date: 2026-08-21 20:54:55.467970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dda6c850acd'
down_revision: Union[str, None] = '414e3d9cfb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('symptoms', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'symptoms')
    # ### end Alembic commands ###
