"""create_ai_summaries_table

Revision ID: 991ae2c72769
Revises: 235b9b3bdfda
Create Date: 2026-08-21 21:17:21.512812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991ae2c72769'
down_revision: Union[str, None] = '235b9b3bdfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('suggested_questions', sa.Text(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_summaries_appointment_id'), 'ai_summaries', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_id'), 'ai_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_summary_type'), 'ai_summaries', ['summary_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_summaries_summary_type'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_id'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_appointment_id'), table_name='ai_summaries')
    op.drop_table('ai_summaries')
    # ### end Alembic commands ###
